//
//  DashboardRouter.swift
//  QRScanner
//
//  Created Jatesh Kumar on 09/04/2021.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Hasnain Kanji
//

import UIKit

final class DashboardRouter {

    weak var viewController: UIViewController?

    deinit {
        print("deinit DashboardRouter")
    }

    static func createModule() -> UIViewController {

        let view = dashboardViewController.instantiateViewController(identifier: "DashboardViewController") as? DashboardViewController

        let interactor = DashboardInteractor()
        let router = DashboardRouter()
        let presenter = DashboardPresenter(interface: view!, interactor: interactor, router: router)

        view!.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view

        return view!
    }
    
    static var dashboardViewController: UIStoryboard {return UIStoryboard(name: "Main", bundle: Bundle.main)}
}

extension DashboardRouter: DashboardWireframeProtocol {
    func openViewController(controller: UIViewController) {
        viewController?.navigationController?.pushViewController(controller, animated: true)
    }
    
    func goBack() {
        viewController?.navigationController?.popViewController(animated: true)
    }
}
