//
//  DashboardProtocols.swift
//  QRScanner
//
//  Created Jatesh Kumar on 09/04/2021.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Hasnain Kanji
//

import UIKit

// MARK: Wireframe -
protocol DashboardWireframeProtocol: class {
    static func createModule() -> UIViewController
}
// MARK: Presenter -
protocol DashboardPresenterProtocol: class {

    var interactor: DashboardInteractorInputProtocol? { get set }

    func openScannerView()
}

// MARK: Interactor -
protocol DashboardInteractorOutputProtocol: class {

    /* Interactor -> Presenter */
}

protocol DashboardInteractorInputProtocol: class {

    var presenter: DashboardInteractorOutputProtocol? { get set }

    /* Presenter -> Interactor */
}

// MARK: View -
protocol DashboardViewProtocol: class {

    var presenter: DashboardPresenterProtocol? { get set }
    func showResults()
}
