//
//  GenerateQR_BarcodeProtocols.swift
//  QRScanner
//
//  Created Jatesh Kumar on 09/04/2021.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Hasnain Kanji
//

import UIKit

// MARK: Wireframe -
protocol GenerateQR_BarcodeWireframeProtocol: class {
    static func createModule () -> UIViewController
}
// MARK: Presenter -
protocol GenerateQR_BarcodePresenterProtocol: class {
    var interactor: GenerateQR_BarcodeInteractorInputProtocol? { get set }
    func GenerateCode(input: String, codeType: Int)
}

// MARK: Interactor -
protocol GenerateQR_BarcodeInteractorOutputProtocol: class {
    func getCodeToDisplay(code: UIImage)
    /* Interactor -> Presenter */
}

protocol GenerateQR_BarcodeInteractorInputProtocol: class {

    var presenter: GenerateQR_BarcodeInteractorOutputProtocol? { get set }
    func GenerateCode(input: String, codeType: Int)
    /* Presenter -> Interactor */
}

// MARK: View -
protocol GenerateQR_BarcodeViewProtocol: class {

    var presenter: GenerateQR_BarcodePresenterProtocol? { get set }

    /* Presenter -> ViewController */
    func displayCode (code: UIImage)
}
