//
//  GenerateQR_BarcodeRouter.swift
//  QRScanner
//
//  Created Jatesh Kumar on 09/04/2021.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Hasnain Kanji
//

import UIKit

final class GenerateQR_BarcodeRouter {

    weak var viewController: UIViewController?

    deinit {
        print("deinit GenerateQR_BarcodeRouter")
    }

    static func createModule(delegate: GenerateQR_BarcodeViewControllerDelegate) -> UIViewController {

        // Change to get view from storyboard if not using progammatic UI
        let view = generateCodeViewController.instantiateViewController(identifier: "GenerateQR_BarcodeViewController") as? GenerateQR_BarcodeViewController
        let interactor = GenerateQR_BarcodeInteractor()
        let router = GenerateQR_BarcodeRouter()
        let presenter = GenerateQR_BarcodePresenter(interface: view!, interactor: interactor, router: router)

        view!.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view
        view!.delegate = delegate.self
        return view!
    }
    
    static var generateCodeViewController: UIStoryboard { return UIStoryboard(name: "Main", bundle: Bundle.main) }
}

extension GenerateQR_BarcodeRouter: GenerateQR_BarcodeWireframeProtocol {
    func navigateToViewController(controller: UIViewController) {
        viewController?.navigationController?.pushViewController(controller, animated: true)
    }
    
    func goBack() {
        viewController?.navigationController?.popViewController(animated: true)
    }
}
