//
//  ScannerProtocols.swift
//  QRScanner
//
//  Created Jatesh Kumar on 09/04/2021.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Hasnain Kanji
//

import UIKit

// MARK: Wireframe -
protocol ScannerWireframeProtocol: class {
    static func createModule() -> UIViewController
}
// MARK: Presenter -
protocol ScannerPresenterProtocol: class {
    var interactor: ScannerInteractorInputProtocol? { get set }
    func openCamera()
}

// MARK: Interactor -
protocol ScannerInteractorOutputProtocol: class {
    func getSession()
    /* Interactor -> Presenter */
}

protocol ScannerInteractorInputProtocol: class {

    var presenter: ScannerInteractorOutputProtocol? { get set }
    func scanQRCode() throws
    /* Presenter -> Interactor */
}

// MARK: View -
protocol ScannerViewProtocol: class {

    var presenter: ScannerPresenterProtocol? { get set }

    /* Presenter -> ViewController */
    
}
